[connections.snowflake]
account = "ELCRZLT-GR44728"
user = "tom.johnson@pebo.com"
password = "1951HockeyGame!"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
